global:
  scrape_interval: 10s
  scrape_timeout: 5s
  evaluation_interval: 10m
  
  external_labels:
    monitor: "server-monitor"

rule_files:
#   - "/var/app/prometheus/alert.rules"

scrape_configs:
  # 監視基盤ホスト の監視
  - job_name: "prometheus_server"
    static_configs:
      - targets: ["localhost:9090"]

  # サーバ の監視
  - job_name: "hostname"
    static_configs:
      - targets: ["hostname:9100"]